### ISSUE TITLE
Rework deployment strategy

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/docs#34]
At the moment, adding docs to this repo is rather painful.

After a new commit is pushed, the docs fail to update. This is probably caused by the force-push we're doing in travis. Somewhy readthedocs fails to detect the change and does not build anything.

**Comment by soffokl** [comment]
@vkuznecovas force push is done to the wiki, not to the repo itself. 
There was missing webhook to trigger readthedoc build for some reasons, it's fixed now.
